### ISSUE TITLE
NetCDF: Malformed or inaccessible DAP DATADDS

### ISSUE THREAD

**Issue by nluchett** [jsillin/SoundingMaps#6]
Hi Jack,

Thanks for sharing this code. I'm here at the NWS Raleigh office and I am trying to run it for our region. When I attempt to run the GFS model, it gives me an error:

NetCDF: Malformed or inaccessible DAP DATADDS

I assumed this must have to do with the web URL that the GFS data is being pulled from. However, when I check the URL in "supplementary_tools.py" it appears that the URL is indeed correct. 

Have you crossed this error before? Any tips on how to solve it? 

Thanks!

Nick Luchetti

**Comment by jsillin** [comment]
Hi Nick, 
This error means that the code can't connect with the right data online. That may mean the URL is constructed wrong (though it sounds like you checked and that's not the case), that NOMADS is having difficulties, or that you're trying to grab the very latest data that isn't quite filled in yet.

I will see if I can reproduce the error on my end.
Thanks for letting me know!
Jack

**Comment by jsillin** [comment]
Just fixed a couple other bugs and got a working map. I will push a small update shortly that is mostly targeted at other issues. Maybe it will help? Otherwise my best guess is that you went looking for the 12z GFS before NOMADS was entirely ready
![raleigh_winter_soundingmap2021-12-07_1200Z](https://user-images.githubusercontent.com/40693187/145077811-6e64ddba-6bde-4a0e-9519-283da390f10e.png)

**Comment by nluchett** [comment]
Hi Jack, 

Thanks for replying! I'll look out for that new version. I'm also having some cartopy issues I'm trying to solve so I'll try this again once I solve them. 

When you choose the region for the map you just created, are you using "north carolina"? Is there specific syntax for user input related to region or local options?

**Comment by jsillin** [comment]
I pushed it a few minutes ago so pulling the repo again should get it in your hands. 

As far as choosing the region, there are two arguments: `domainsize` which, for now, must be either "local" (~WFO sized) or "regional" (what I have in my map above) and `domainname` which can be whatever you want to keep the files straight.

My full settings for that image were:
```
    domainsize='regional'
    domainname='raleigh'
    centerlat = 35.8
    centerlon = 78.8
    model = 'GFS'
    cape_input = 'no'
    wetbulb_input = 'yes'
    season = 'winter'
```

Hope this helps and if you're getting other errors, feel free to post those too!

**Comment by nluchett** [comment]
Hey Jack,

I was able to get it running to a certain extent with your new version. However, the plotting is a bit off.  See attached image for my output:

![raleigh_winter_soundingmap2021-12-07_1200Z](https://user-images.githubusercontent.com/49732308/145104412-0c4cc3c1-ebec-4f93-bcea-a3ce1064a1f8.png)

How did you get such a clean plot in the comment you posted earlier? It seems that my output does not include sounding data from above a certain latitude, while your plot does (in PA for example). I ran it with the same user inputs as you mention above:

 domainsize='regional'
    domainname='raleigh'
    centerlat = 35.8
    centerlon = 78.8
    model = 'GFS'
    cape_input = 'no'
    wetbulb_input = 'yes'
    season = 'winter'

**Comment by jsillin** [comment]
hmm yeah that's not how it's supposed to look!

I just pushed another fix for the various bugs I think you found earlier. Shame on me for not testing that enough before I pushed it out! I just tested my new version and all looks good so there are two possibilities in my mind:
1. something broke when you went to fix my earlier bugs, in which case grabbing my bugfix should solve it
2. you're using newer or older versions of some of the packages on which this is built and something is going awry there (cartopy maybe? Metpy? Matplolib? not sure). If pulling the latest code doesn't work (again so sorry about that), why don't you send me a list of the exact versions of each package (or even better a yml file if you're familiar with those) so I can construct an identical environment and see if I can replicate the error

**Comment by nluchett** [comment]
Hey Jack,

Thanks for fixing the else indent issues. I grabbed the new code you pushed and it ran fine this time. However, the plotting issues are still present. 

Here is my current versions I'm using of various packages:

Cartopy: 0.18.0
Metpy: 1.1.0
matplotlib: 3.4.3

I'm not too familiar with YML files, is it easy to produce these? If so, I can try if you have any advice!

Thanks alot for the help!

Nick

**Comment by jsillin** [comment]
Opened new issue for the plotting.

As for the initial malformed DAP DATADDS issue, I sometimes will get it but it resolves after simply re-running the script. This isn't terrible but it's annoying especially in an operational context/for people who aren't as deep into the weeds of python. I think to fix this I will need to update my data fetching backend to use UCAR/Unidata THREDDS which is more robust than NOMADS
